### ISSUE TITLE
News page

### ISSUE THREAD

**Issue by robinsph21** [upcs/cs341-project-ss2020-ada#46]
The first two news pages show up nicely, but the following news stories do not show up with styling. There appears to be more issues on the same page

**Comment by slemly** [comment]
The tool we use to embed the news articles sometimes takes a while. We will look into adding a loading screen or some placeholder while those assets load.

**Comment by slemly** [comment]
We have added a loading wheel to the page; it's difficult to test locally because the assets load extremely quickly. You might see some unstyled HTML for about half a second before everything snaps into place.
