### ISSUE TITLE
No button to get home in the login screen

### ISSUE THREAD

**Issue by mikerichantk** [upcs/cs341-project-ss2020-ada#47]
I am in the login page and there is no button to get back home besides the back arrow in the browser

**Comment by bunger20** [comment]
A little more detail on this (or a related complain): You get a log out button on the same area as you enter passwords...
<img width="1411" alt="Screen Shot 2020-04-02 at 10 40 36 AM" src="https://user-images.githubusercontent.com/45083922/78281180-2372cd80-74cf-11ea-85c7-bc16debc89c4.png">

**Comment by pirkl21** [comment]
Hi! for the original comment, clicking the cancel button on the bottom will return you to the home-page! For the second comment, thanks for noting that! We have been meaning to make some changes regarding this issue but were unable to get to them this sprint.
