### ISSUE TITLE
Bug with show/hide data

### ISSUE THREAD

**Issue by hojo21** [upcs/cs341-project-ss2020-ada#53]
Show/hide doesn't work. Bug with duplicate points and colors:
1. Enter Street Address: 97203 and Name: 1 with color red
2. Save location
3. Enter Street Address: 97204 and Name: 2 with color blue
4. Save location
5. Change color to green
6. Save location and close pop-up
7. Toggle show/hide data

**Comment by harrah20** [comment]
fixed by fixing a different bug
